// Embed the sealed string table and the trigger table into a JS module, so
// the bundle carries the canon at build time (the game must never fetch) and
// Node can import it without a loader. Source of truth is canon/; run this
// after any change there:  npm run canon:embed
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const vault = fs.readFileSync(path.join(root, "canon/vault/strings.vault"), "utf8");
const triggers = fs.readFileSync(path.join(root, "canon/bible/triggers.json"), "utf8");
const out = `/*!
 * GENERATED by tools/canon-embed.mjs from canon/vault/strings.vault and
 * canon/bible/triggers.json. Do not edit; edit canon/ and re-run.
 * The vault is sealed prose: leave it sealed.
 */

export const STRINGS_VAULT = ${JSON.stringify(vault)};

export const TRIGGERS = ${JSON.stringify(JSON.parse(triggers))};
`;
const dst = path.join(root, "src/canon/embed.js");
if (process.argv.includes("--check")) {
  const cur = fs.existsSync(dst) ? fs.readFileSync(dst, "utf8") : "";
  if (cur !== out) { console.error("src/canon/embed.js is stale: run npm run canon:embed"); process.exit(1); }
  console.log("canon embed is current");
} else {
  fs.writeFileSync(dst, out);
  console.log("wrote", path.relative(root, dst));
}
